title: Digital Archives
description: This site documents the policies and procedures of the MOHAI Digital Archives program, which manages the
  born-digital portions of archival acquisitions by the Sophie Bass Frye Library. 
theme: just-the-docs
nav_order: 4

url: https://sophiebassfryelibrary.github.io/digi-pres-docs/

logo: "/assets/images/mohai-logo.png"

aux_links:
  Collections Homepage: https://mohai.org/collections-and-research/
