title: MOHAI Digital Archives
description: Digital preservation documentation for MOHAI's Sophie Bass Frye Library.
theme: just-the-docs

url: https://sophiebassfryelibrary.github.io/digi-pres-docs/

aux_links:
  Collections Homepage: https://mohai.org/collections-and-research/
